[package]
name = "take-on-tokio"
version = "0.1.0"
authors = ["RT <k.teza1@gmail.com>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
openssl = "0.8"
tokio-tls = { git = "https://github.com/tokio-rs/tokio-tls" }